### ISSUE TITLE
ValueError: illegal image mode

### ISSUE THREAD

**Issue by Nux-xader** [Zarcher0/BootAnimationMaker#2]
im trying make boot animation using some example in this repository but im getting this error

gifsicle.exe: warning: trivial adaptive palette (only 31 colors in source)
Traceback (most recent call last):
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\run.py", line 397, in <module>
    main()
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\run.py", line 249, in main
    gif2png(
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\ImgProcess.py", line 45, in gif2png
    frame.putpalette(p)
  File "C:\Users\satri\OneDrive\Documents\BootAnimationMaker\env\lib\site-packages\PIL\Image.py", line 1914, in putpalette
    raise ValueError(msg)
ValueError: illegal image mode

**Comment by koro33e** [comment]
Fixed, but a workaround solution. All given examples should be ok.

**Comment by koro33e** [comment]
BTW, this might be related to the new version of `pillow`. I don't want to dig more into it, bcs this repository is too old, and the method to write a config file to deal with image is actully not so smart.
